#include "oct2dq_run_settings.h"
#include "process.h" 
#include <iostream>

/**
 * @file   main.cpp
 * @author Eric Turner <elturner@eecs.berkeley.edu>
 * @brief  Will form wall samples from an octree
 *
 * @section DESCRIPTION
 *
 * This is the main file for the octree surface reconstruction program
 * (oct2dq) which will generate a surface reconstruction of a building
 * interior environment from an octree generated by procarve.
 */

using namespace std;

/* function implementations */

/**
 * The main function for this program
 */
int main(int argc, char** argv)
{
	oct2dq_run_settings_t args;
	process_t process;
	int ret;

	/* parse the given parameters */
	ret = args.parse(argc, argv);
	if(ret)
	{
		cerr << "[main]\tError " << ret << ": "
		     << "Could not parse parameters" << endl;
		return 1;
	}

	/* initialize the data to process */
	ret = process.init(args);
	if(ret)
	{
		cerr << "[main]\tError " << ret << ": "
		     << "Unable to initialize data" << endl;
		return 2;
	}

	// TODO

	/* success */
	return 0;
}
