#include "octsurf_run_settings.h"
#include <iostream>

/**
 * @file main.cpp
 * @author Eric Turner <elturner@eecs.berkeley.edu>
 *
 * @section DESCRIPTION
 *
 * This is the main file for the octree surface reconstruction program
 * (octsurf) which will generate a surface reconstruction of a building
 * interior environment from an octree generated by procarve.
 */

using namespace std;

/* function implementations */

#include <io/octree/tree_exporter.h>
#include <io/octree/vox_writer.h>
#include <geometry/octree/octree.h>

/**
 * The main function for this program
 */
int main(int argc, char** argv)
{
	octsurf_run_settings_t args;
	octree_t tree;
	int ret;

	/* parse the given parameters */
	ret = args.parse(argc, argv);
	if(ret)
	{
		cerr << "[main]\tError " << ret << ": "
		     << "Could not parse parameters" << endl;
		return 1;
	}

	/* initialize */
	ret = tree.parse(args.octfiles[0]);
	if(ret)
	{
		cerr << "[main]\tError " << ret << ": "
		     << "Unable to read octfile." << endl;
		return 2;
	}

	/* export */
	switch(args.output_format)
	{
		default:
			/* unable to export to this file format */
			cerr << "[main]\tUnknown file extension provided"
			     << " for output file: " << args.outfile
			     << endl;
			break;
		case FORMAT_VOX:
			/* export tree as vox file */
			ret = vox_writer_t::write(args.outfile, tree);
			if(ret)
			{
				cerr << "[main]\tError " << ret << ": "
				     << "Unable to export to vox" << endl;
				return 3;
			}
			break;
		case FORMAT_OBJ:
			/* export basic obj file */
			ret = tree_exporter::export_leafs_to_obj(
					args.outfile, tree);
			if(ret)
			{
				cerr << "[main]\tError " << ret << ": "
				     << "Unable to export to obj" << endl;
				return 4;
			}
			break;
		case FORMAT_TXT:
			/* export useful stats to txt */
			ret = tree_exporter::export_stats_to_txt(
					args.outfile, tree);
			if(ret)
			{
				cerr << "[main]\tError " << ret << ": "
				     << "Unable to export to txt" << endl;
				return 5;
			}
			break;
	}

	/* success */
	return 0;
}
