#include <iostream>

/**
 * @file main.cpp
 * @author Eric Turner <elturner@eecs.berkeley.edu>
 *
 * @section DESCRIPTION
 *
 * This is the main file for the octree surface reconstruction program
 * (octsurf) which will generate a surface reconstruction of a building
 * interior environment from an octree generated by procarve.
 */

using namespace std;

/* function implementations */

#include <io/octree/tree_exporter.h>
#include <geometry/octree/octree.h>

/**
 * The main function for this program
 */
int main()
{
	octree_t tree;
	int ret;
	
	/* set input files */
	string dataset = "/home/elturner/Desktop/data/20131204-16/";
	string octfile = dataset + "models/carving/ref_carving.oct";
	string objfile = "/home/elturner/Desktop/test.obj";

	/* initialize */
	ret = tree.parse(octfile);
	if(ret)
	{
		cerr << "Unable to read octfile, error: " << ret << endl;
		return 1;
	}

	cout << "input tree # nodes: " << tree.get_root()->get_num_nodes()
	     << endl;

	/* export */
	ret = tree_exporter::export_leafs_to_obj(objfile, tree);
	if(ret)
	{
		cerr << "Unable to export to obj, error: " << ret << endl;
		return 2;
	}

	/* success */
	return 0;
}
