#ifndef HMC_DATA_READER_H
#define HMC_DATA_READER_H

/**
 * @file hmc_data_reader.h
 * @author Eric Turner <elturner@eecs.berkeley.edu>
 *
 * @section DESCRIPTION
 *
 * This file contains definitions for classes used to read and
 * parse the output data files generated by running the data
 * acquisition code with magnetometer.  The HMC magnetometer
 * generates a binary data file to be parsed.
 */

#include <fstream>
#include <istream>
#include <string>

/* the following classes are defined in this file */
class hmc_frame_t;
class hmc_reader_t;

/**
 * This classes defines one scan line from a Hakuyo HMC data file
 */
class hmc_frame_t
{
	/* parameters */
	public:

		/* The index of this scan frame */
		unsigned int index;

		/* Each reading from the magnetometers has one single
		 * timestamp, but readings from every sensor
		 *
		 * All values have been converted to host endianness,
		 * which has been assumed to be little-endian */
		
		/* the temperature timestamp and reading */
		double timestamp; /* units: seconds */

		/* the number of sensors used */
		unsigned int num_sensors;

		/* the vector readings */
		unsigned short* readings_x; /* array of x-coordinates */
		unsigned short* readings_y; /* array of y-coordinates */
		unsigned short* readings_z; /* array of z-coordinates */

	/* functions */
	public:

		/* constructors */

		/**
		 * Initializes empty frame
		 */
		hmc_frame_t();

		/**
		 * Frees all memory and resources
		 */
		~hmc_frame_t();

		/* initialization */

		/**
		 * Will parse the next scan block out of a binary stream
		 *
		 * The stream is assumed to be a hmc data file, positioned
		 * at the start of a scan block.  The scan block will be
		 * parsed based to populate this struct.
		 *
		 * @param is           The binary stream to read and parse
		 * @param conversion_to_seconds    For timestamping
		 * @param ns           Number of sensors collecting data
		 *
		 * @returns    Returns zero on success, non-zero on failure
		 */
		int parse(std::istream& is, double conversion_to_seconds,
		          unsigned char ns);
};

/**
 * This defines the hmc_reader_t class to parse a binary 
 * magnetometer data file
 */ 
class hmc_reader_t
{
	/* parameters */
	private:

		/* the binary file to parse */
		std::ifstream infile;

		/* the number of frames read so far from the file */
		unsigned int next_index;

		/* the version numbers of the file */
		char major_version;
		char minor_version;

		/* metadata about the capture */
		unsigned char num_sensors; /* number of magnetometers */
		double gain; /* conversion between LSB units and gauss */
		double conversion_to_seconds; /* for timestamps */

		/* size of file */
		unsigned int num_scans;

	/* functions */
	public:

		/* constructors */

		/**
		 * Constructs empty class
		 */
		hmc_reader_t();

		/**
		 * Frees all allocated memory and resources
		 */
		~hmc_reader_t();

		/**
		 * Open file for parsing. Verifies file correctly formatted.
		 *
		 * Will open the selected file, and read the header of
		 * this file.  Will only return success if the file
		 * is verified to be a magnetometer binary data file.  After
		 * this is called, will be ready to read scan frames from
		 * file.
		 *
		 * @param filename The path to magnetometer binary data file
		 *
		 * @returns     Returns zero on success, non-zero on failure
		 */
		int open(const std::string& filename);

		/**
		 * Parses the next frame from the file
		 *
		 * Will read the next frame from the file and populate
		 * the specified frame struct with its information.
		 *
		 * @param frame The struct to populate with the next frame
		 *
		 * @returns     Returns zero on success, non-zero on failure
		 */
		int next(hmc_frame_t& frame);

		/**
		 * Returns true iff end of file reached.
		 *
		 * Will pass the eof flag from the file stream as
		 * the return value of this function.
		 *
		 * @returns     Returns true iff end-of-file reached
		 */
		bool eof() const;

		/**
		 * Closes the stream and frees resources
		 *
		 * Will close any open file streams and free allocated
		 * arrays in memory.
		 */
		void close();
};

#endif
