#!/usr/bin/python

##
# @file create_models.py
# @author Eric Turner <elturner@eecs.berkeley.edu>
#
# @section DESCRIPTION
#
# This script will generate all modeling products, such as pointclouds,
# floorplans, and 3D models.  This should be called after the localization
# is completed for a dataset.
#
# Usage:
#
#	python create_models.py <path_to_dataset> <localization_file>
#

import os
import sys
import shutil
import subprocess

# Get the location of this file
SCRIPT_LOCATION = os.path.dirname(__file__)

# Import the config
PYTHON_SRC_DIR = os.path.abspath(os.path.join(SCRIPT_LOCATION, \
                                 '..', 'src','python'))
sys.path.append(PYTHON_SRC_DIR)
import config

###################################
##### PARSE COMMAND ARGUMENTS #####
###################################

# check that we were given a command-line argument
if len(sys.argv) != 3:
	print ""
	print " Usage:"
	print ""
	print "\t",sys.argv[0],"<path_to_dataset>","<localization_file>"
	print ""
	sys.exit(1)

# Get the dataset directory from command-line
DATASET_DIR = sys.argv[1]

# verify this is a valid folder
if not os.path.exists(DATASET_DIR):
	print "Error!  This is not a valid directory:",DATASET_DIR
	sys.exit(2)

# Get the output file from localization
LOCALIZATION_FILE = sys.argv[2]
if not os.path.exists(LOCALIZATION_FILE):
	print "Error! This is not a valid file:",LOCALIZATION_FILE
	sys.exit(3)

# get the human-friendly name of this dataset from the input file
(loc_file_head, loc_file_tail) = os.path.split(LOCALIZATION_FILE)
(DATASET_NAME, loc_file_ext) = os.path.splitext(loc_file_tail)

################################
##### Executable Locations #####
################################

# Set the location of the binaries
EXE_DIR = os.path.join(SCRIPT_LOCATION,'..','bin')

# The following locations are relative paths from the 'scripts/' folder
POINTCLOUD_EXE = os.path.abspath(os.path.join(EXE_DIR,  "pointcloud_gen"))
PART_PC_LEVELS_EXE = os.path.abspath(os.path.join(EXE_DIR, \
                                     "partition_pointcloud_levels"))
XYZ2DQ_EXE     = os.path.abspath(os.path.join(EXE_DIR,  "xyz2dq"))
FLOORPLAN_EXE  = os.path.abspath(os.path.join(EXE_DIR,  "floorplan_gen"))
FP2MODEL_EXE   = os.path.abspath(os.path.join(EXE_DIR,  "fp2model"))
FP2MODEL_TEXTURE_DIR = os.path.abspath(os.path.join(SCRIPT_LOCATION, \
                                       "..","execs","fp2model","texture"))
if sys.platform == 'win32' :
	TIME_SYNC_EXE += '.exe'
	BAYER_EXE += '.exe'

# Verify that these executables exist
if not os.path.exists(POINTCLOUD_EXE):
	print "Error!  Could not find pointcloud generation executable:", \
	      POINTCLOUD_EXE
	sys.exit(4)

if not os.path.exists(PART_PC_LEVELS_EXE):
	print "Error!  Could not find", \
	      "pointcloud level partitioning executable:", \
	      PART_PC_LEVELS_EXE
	sys.exit(5)

if not os.path.exists(XYZ2DQ_EXE):
	print "Error!  Could not find wall sampling executable:", \
	      XYZ2DQ_EXE
	sys.exit(6)

if not os.path.exists(FLOORPLAN_EXE):
	print "Error!  Could not find floorplan executable:", \
	      FLOORPLAN_EXE
	sys.exit(7)

if not os.path.exists(FP2MODEL_EXE):
	print "Error!  Could not find floorplan -> model executable:", \
	      FP2MODEL_EXE
	sys.exit(8)

################################
##### Input File Locations #####
################################

# These files are generated by the data acquisition, preprocessing,
# or localization.  They are assumed to be in the following locations.
hardware_config_xml     = os.path.join("config","backpack_config.xml")
time_sync_xml           = os.path.join("time","time_sync.xml")

# These are sensor-specific files and values
geom_scanner_name       = "H1214157"
geom_scanner_datafile   = os.path.join("data", "urg", geom_scanner_name, \
                                       "urg_" + geom_scanner_name \
                                       + "_scandata.dat")
left_camera_dir         = os.path.join("data", "dalsa", "left_camera", \
                                       "color")
left_camera_metadata    = os.path.join("data", "dalsa", "left_camera", \
                                       "color_left_camera_metadata.txt")
left_camera_calib       = os.path.join("calib", "camera", "intrinsic", \
                                       "ocam_calib_left.dat")
right_camera_dir         = os.path.join("data","dalsa","right_camera", \
                                        "color")
right_camera_metadata    = os.path.join("data", "dalsa", \
                                        "right_camera", \
                                        "color_right_camera_metadata.txt")
right_camera_calib       = os.path.join("calib", "camera", "intrinsic", \
                                        "ocam_calib_right.dat")

#################################
##### Output File Locations #####
#################################

# The following folders will contain the output files of this script,
# so we need to verify that they exist
MODELS_DIR     = os.path.join(DATASET_DIR, "models")
if not os.path.exists(MODELS_DIR):
	os.makedirs(MODELS_DIR)

POINTCLOUD_DIR = os.path.join(MODELS_DIR, "pointclouds")
if not os.path.exists(POINTCLOUD_DIR):
	os.makedirs(POINTCLOUD_DIR)

PC_LEVELS_DIR  = os.path.join(POINTCLOUD_DIR, "levels")
if not os.path.exists(PC_LEVELS_DIR):
	os.makedirs(PC_LEVELS_DIR)

FLOORPLAN_DIR  = os.path.join(MODELS_DIR, "floorplan")
if not os.path.exists(FLOORPLAN_DIR):
	os.makedirs(FLOORPLAN_DIR)

# The following files will be generated by the executables called by
# this script
mad_file        = LOCALIZATION_FILE
xyz_file        = os.path.join(POINTCLOUD_DIR, DATASET_NAME + "_full.xyz")
xyz_levels      = os.path.join(PC_LEVELS_DIR,  DATASET_NAME + "_level_")
xyz_hist        = os.path.join(PC_LEVELS_DIR,  DATASET_NAME + "_hist.m")
dq_file         = os.path.join(FLOORPLAN_DIR,  "wall_samples.dq")
fp_file         = os.path.join(FLOORPLAN_DIR,  DATASET_NAME + ".fp")
texture_dir     = os.path.join(FLOORPLAN_DIR,  "texture")
obj_file        = os.path.join(texture_dir,  DATASET_NAME + ".obj")

####################
##### RUN CODE #####
####################

print "#### GENERATING FILES FOR %s ####" % DATASET_NAME
print ""

#################################
##### POINTCLOUD GENERATION #####
#################################

print "##### creating colored pointcloud #####"
ret = subprocess.call([POINTCLOUD_EXE, \
                      "-c", hardware_config_xml, \
                      "-f", left_camera_metadata, left_camera_calib, \
                            left_camera_dir, \
                      "-f", right_camera_metadata, right_camera_calib, \
                            right_camera_dir, \
                      "-l", geom_scanner_name, geom_scanner_datafile, \
                      "-o", xyz_file, \
                      "-p", LOCALIZATION_FILE, \
                      "-t", time_sync_xml, \
                      "-u", "1000"], \
                      executable=POINTCLOUD_EXE, cwd=DATASET_DIR, \
                      stdout=None, stderr=None, stdin=None, shell=False)
if ret != 0:
	print "Error! Pointcloud generation program returned",ret
	sys.exit(9)

###################################
##### POINTCLOUD PARTITIONING #####
###################################

print "##### partitioning pointcloud into different floors #####"
ret = subprocess.call([PART_PC_LEVELS_EXE, \
                      "-o", xyz_levels, mad_file, \
                      xyz_file, xyz_hist], \
                      executable=PART_PC_LEVELS_EXE, cwd=DATASET_DIR, \
                      stdout=None, stderr=None, stdin=None, shell=False)
if ret != 0:
	print "Error! Pointcloud partitioning program returned",ret
	sys.exit(10)

# TODO look at this output and use it for further processing

#########################
##### WALL SAMPLING #####
#########################

print "##### generating wall samples from pointcloud data #####"
ret = subprocess.call([XYZ2DQ_EXE, \
                      xyz_file, dq_file, mad_file], \
                      executable=XYZ2DQ_EXE, cwd=DATASET_DIR, \
                      stdout=None, stderr=None, stdin=None, shell=False)
if ret != 0:
	print "Error! Wall sampling program returned",ret
	sys.exit(11)

################################
##### FLOORPLAN GENERATION #####
################################

# make floorplan from wall samples
print "##### generating floor plans #####"
ret = subprocess.call([FLOORPLAN_EXE, \
                      dq_file, mad_file, fp_file], \
                      executable=FLOORPLAN_EXE, cwd=DATASET_DIR, \
                      stdout=None, stderr=None, stdin=None, shell=False)
if ret != 0:
	print "Error! Floorplan generation program returned",ret
	sys.exit(12)

# copy over texture directory for model
if not os.path.exists(texture_dir):
	shutil.copytree(FP2MODEL_TEXTURE_DIR, texture_dir) 

# make obj from floorplan
print "##### generating extruded model #####"
ret = subprocess.call([FP2MODEL_EXE, \
                      obj_file, fp_file], \
                      executable=FP2MODEL_EXE, cwd=DATASET_DIR, \
                      stdout=None, stderr=None, stdin=None, shell=False)
if ret != 0:
	print "Error! Floorplan->model program returned",ret
